### ISSUE TITLE
won't build on ubuntu 18.04

### ISSUE THREAD

**Issue by muscleman** [freelacoin/freelabit#3]
/home/yiimpserver/freelabit-1.1/src/Common/Base58.cpp:90:32: error: this statement may fall through [-Werror=implicit-fallthrough=]
         case 1:            res |= *data++;
                            ~~~~^~~~~~~~~~
/home/yiimpserver/freelabit-1.1/src/Common/Base58.cpp:91:9: note: here
         case 2: res <<= 8; res |= *data++;
         ^~~~
/home/yiimpserver/freelabit-1.1/src/Common/Base58.cpp:91:32: error: this statement may fall through [-Werror=implicit-fallthrough=]
         case 2: res <<= 8; res |= *data++;
                            ~~~~^~~~~~~~~~
/home/yiimpserver/freelabit-1.1/src/Common/Base58.cpp:92:9: note: here
         case 3: res <<= 8; res |= *data++;
         ^~~~
/home/yiimpserver/freelabit-1.1/src/Common/Base58.cpp:92:32: error: this statement may fall through [-Werror=implicit-fallthrough=]
         case 3: res <<= 8; res |= *data++;
                            ~~~~^~~~~~~~~~
/home/yiimpserver/freelabit-1.1/src/Common/Base58.cpp:93:9: note: here
         case 4: res <<= 8; res |= *data++;
         ^~~~
/home/yiimpserver/freelabit-1.1/src/Common/Base58.cpp:93:32: error: this statement may fall through [-Werror=implicit-fallthrough=]
         case 4: res <<= 8; res |= *data++;
                            ~~~~^~~~~~~~~~
/home/yiimpserver/freelabit-1.1/src/Common/Base58.cpp:94:9: note: here
         case 5: res <<= 8; res |= *data++;
         ^~~~
/home/yiimpserver/freelabit-1.1/src/Common/Base58.cpp:94:32: error: this statement may fall through [-Werror=implicit-fallthrough=]
         case 5: res <<= 8; res |= *data++;
                            ~~~~^~~~~~~~~~
/home/yiimpserver/freelabit-1.1/src/Common/Base58.cpp:95:9: note: here
         case 6: res <<= 8; res |= *data++;
         ^~~~
/home/yiimpserver/freelabit-1.1/src/Common/Base58.cpp:95:32: error: this statement may fall through [-Werror=implicit-fallthrough=]
         case 6: res <<= 8; res |= *data++;
                            ~~~~^~~~~~~~~~
/home/yiimpserver/freelabit-1.1/src/Common/Base58.cpp:96:9: note: here
         case 7: res <<= 8; res |= *data++;
         ^~~~
/home/yiimpserver/freelabit-1.1/src/Common/Base58.cpp:96:32: error: this statement may fall through [-Werror=implicit-fallthrough=]
         case 7: res <<= 8; res |= *data++;
                            ~~~~^~~~~~~~~~
/home/yiimpserver/freelabit-1.1/src/Common/Base58.cpp:97:9: note: here
         case 8: res <<= 8; res |= *data; break;
         ^~~~
cc1plus: all warnings being treated as errors

**Comment by freelacoin** [comment]
Use Ubuntu 16
